### ISSUE TITLE
100W or even more - which parts to be changed on the PCB? 

### ISSUE THREAD

**Issue by fafu** [elektra42/freifunk-open-mppt#3]
Hi all,
since 100W solar panels are only slightly more expensive than a 50W panel I am curious which parts to be changed. If I remember right, elektra told me during a workshop it is possible. 

Thanks :)

**Comment by elektra42** [comment]
You should replace C6, Q2 and C13. Replace C6 with a polymer electrolytic capacitor, they have lowest ESR compared to the stock low ESR capacitor. Recommended: PANASONIC SVPF 330µ 25 V. Replace C13  with a polymer electrolytic capacitor. Recommended: PANASONIC SVPF 1000µ 16V , Replace Q2 with AO D403 MOSFET, P-CH, 30V, 70A, 90W, DPAK. 

Make sure to not exceed 25 V idle (open connector = Voc) solar panel voltage in sunny, but freezing cold climate (sunny winter day). The absolute maximum voltage limit of SVPF 330µ 25 V is 29 V. You should avoid getting close to that limit. If you risk 26 or even 27 V idle under rare conditions, that might be ok. Keep an eye on L1, on my tuned FF-OpenMPPTs, I have used a larger ring power core with thicker wire, so I'd recommend that, too. But you might get away with the stock L1. If you buy a bigger ring power core L1 could be winded to ~16µH, if possible with thicker insulated copper wire. The thicker the wire you can make fit, the better (more efficient).

As I sidenote: I have a new design with a ESP32 build in and prepared for more power. https://github.com/ISEMS/ISEMS-ESP32

Have fun and success with soldering.

Sunshine!
Elektra

**Comment by elektra42** [comment]
One more note: The material for the ring power core is critical. So don't use just a random ring power core that comes your way. I recommend Micrometals/Amidon power core material type "-18", a T 94-18 should handle the power well.

**Comment by fafu** [comment]
Thank you for the helpful information
