### ISSUE TITLE
Max current on v-out? 

### ISSUE THREAD

**Issue by fafu** [elektra42/freifunk-open-mppt#4]
Hi,
what is the max current which can be drawn on v-out?

**Comment by elektra42** [comment]
RDS_on is 0.06 Ohm for the stock IRF5305. For a output current of 5 Ampere this means a voltage drop of 0.3 V and a power loss of 1.5 Watt. You can upgrade to a AO D403 here, too, which has 0.008 Ohm RDS_on. That results in a voltage drop of 0.08 V at 10 Ampere, hence a power loss of 0.8 Watt. I recommend not to go higher than that.
